### ISSUE TITLE
Make Upgrades Look Better

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/autohack-idle#134] opened 2024-07-10 17:47 UTC
Currently the upgrades are a little tight - not much padding, kind of hard to read, not clear what they all do. They should be made to look cleaner and more obvious. Also #15

**Comment by jvgusch** [comment] 2024-07-23 17:06
Duplicate of #15. Closing.

**Closed** 2024-07-23 17:07 UTC
Labels: bug
